### PR TITLE
blockchain: rename to core

### PR DESCRIPTION
**Pull request by marbar3778**
This pr renames blockchain to core. Personally I don't find blockchain that descriptive and a bit confusing as the entire spec describes a blockchain protocol. 

I am willing to rename core to something else, core is the first thing the came to mind. 

ref #121

### CODE REVIEW

**Comment by josef-widder** [comment]
Renaming blockchain.md to datastructures.md etc. makes a lot of sense! I already have some plan what could go into a blockchain.md file in the future ;-)

**Comment by ebuchman** [comment]
This will break a lot of external links. Might be nice to keep the old folder around with empty files that just say "Deprecated" and point to the new location ...

**Comment by marbar3778** [comment]
> This will break a lot of external links. Might be nice to keep the old folder around with empty files that just say "Deprecated" and point to the new location ...

there are a few locations in Tendermint where this is the case. I would prefer to replace the old links with permalinks instead of keeping deprecated files around. Do you know of any other locations?

**Comment by josef-widder** [comment]
We also refer to it in several specification here: https://github.com/informalsystems/tendermint-rs/tree/master/docs/spec

**Comment by ebuchman** [comment]
Off hand I could imagine:

- repo docs in tendermint, cosmos-sdk, ics. others?
- websites and blog posts, eg. in tendermint and cosmos medium, etc.
- informal systems specs and papers 

You're right we should be using permalinks more. Sometimes there's incentive to use a non-perma-link because you know you're still working on it  and want the link to point to the latest. 

I don't know what the right solution is 🤷‍♂️

**Comment by marbar3778** [comment]
ill add empty files. When we go to refactor the docs and specs then we can worry about removing them

**Comment by marbar3778** [comment]
please see #103

**Pull request merged**
