### PR TITLE
genesis: remove app_hash 

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

Remove app_hash from genesis as it is not used and returned by the app on initchain.

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]
Yup this makes sense to me 👍

**Comment by josef-widder** [comment]
So that was once used and is not used anymore, or what is the reason it was there in the first place?

**Comment by marbar3778** [comment]
I looked back through some issues and couldn't find why it was there. Maybe @ebuchman could shed some light. I mainly know its not used now.

**Comment by marbar3778** [comment]
@milosevic do you have thoughts here?

**Comment by marbar3778** [comment]
@ebuchman could I get your approval here?

**Pull request closed without merging**
