### PR TITLE
spec: move reactor level specs to tendermint repo

### PR DESCRIPTION
**Pull request by marbar3778**
The reactor specs are implementation level and should not live with the client agnostic specs.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
So, there's a few different things being covered by this. The actual reactor implementation details should not live in the spec repo, but the descriptions and specifics of the P2P protocols should be in the repo. This includes stuff like messages, channel IDs, and the protocol semantics.

**Comment by marbar3778** [comment]
making this a draft pr as a lot of the specs are intertwined right now.

**Comment by marbar3778** [comment]
TODO:
[ ] add channels IDs
[ ] add p2p protocol messages
[ ] add encoding information. (Amino as 0.34 is not yet released)

**Comment by marbar3778** [comment]
closing this due to discussion in the last dev call

**Pull request closed without merging**
